export enum SidebarGroup {
  PRODUCTS = 'SIDEBAR_GROUP_PRODUCTS',
  SALARIES = 'SIDEBAR_GROUP_SALARIES',
  EMPLOYEES = 'SIDEBAR_GROUP_EMPLOYEES',
  OTHER = 'SIDEBAR_GROUP_OTHER',
}

export enum SidebarTab {
  ADDING_QUANTITY = 'SIDEBAR_TAB_ADDING_QUANTITY',
  PRODUCTS_MANAGEMENT = 'SIDEBAR_TAB_PRODUCTS_MANAGEMENT',
  SALARIES = 'SIDEBAR_TAB_SALARIES',
  PRINTING_SUMMARIES = 'SIDEBAR_TAB_PRINTING_SUMMARIES',
  EMPLOYEES_MANAGEMENT = 'SIDEBAR_TAB_EMPLOYEES_MANAGEMENT',
  LOGS = 'SIDEBAR_TAB_LOGS',
}
