query GetFilteredSalaries($year: Int!, $month: Int!) {
  salaries(filters: { year: { eq: $year }, month: { eq: $month } }) {
    data {
      attributes {
        salary
        employee {
          data {
            attributes {
              firstName
              lastName
            }
          }
        }
      }
    }
  }
}
