query GetLogs($page: Int = 1, $pageSize: Int = 100) {
  logs(pagination: { page: $page, pageSize: $pageSize }) {
    data {
      id
      attributes {
        date
        type
        description
        users_permissions_user {
          data {
            id
            attributes {
              email
            }
          }
        }
      }
    }
  }
}
