query GetProducts {
  products {
    data {
      id
      attributes {
        code
        name
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
