query GetProducts {
  products(filters: { deleted: { eq: false } }) {
    data {
      id
      attributes {
        code
        name
        price
        active
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
