query GetQuantities($workerId: ID!, $year: Int!, $month: Int!) {
  quantities(filters: { year: { eq: $year }, month: { eq: $month }, employee: { id: { eq: $workerId } } }) {
    data {
      id
      attributes {
        quantity
        product {
          data {
            id
            attributes {
              code
              name
              price
            }
          }
        }
      }
    }
  }
}
