query GetSalaries {
  salaries {
    data {
      attributes {
        salary
        employee {
          data {
            attributes {
              firstName
              lastName
            }
          }
        }
      }
    }
  }
}
